<section id="card">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card clickable-card">
                    <div class="card-img">
                        <img src="https://placehold.co/300x200" alt="Card Background" class="background-image">
                        <div class="logo-container">
                            <img src="http://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png" alt="Logo" class="logo-img">
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-text-container">
                            <span class="card-title">TyroSiteFrameWork</span>
                            <i class="ri-heart-3-line heart-icon"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>

#card {
    margin-top: 20px;
}

.card {
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    background-color: white;
    transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.card:hover {
    transform: scale(1.02);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
}

.card-img {
    position: relative;
    height: 200px;
}

.background-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    filter: blur(5px)

}

.logo-container {
    position: absolute;
    background-color: white;
    border-radius: ;
}

.logo-img {
    width: 60px;
    height: 60px;
}

.card-body {
    padding: 10px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid rgba(0,0,0,0.1);
}

.card-title {
    font-size: 16px;
    font-weight: bold;
    color: black;

}

</style>