<?php

$allLabs = getAllLabs();

?>

<section id="card">
    <div class="container">
        <div class="row">
            <?php
                foreach ($allLabs as $lab) { ?>
                        <div class="col-md-6" onclick="window.location.href = 'show.php?l=<?= $lab['id'] ?>'; ">
                            <div class="card clickable-card">
                                <div class="card-img">
                                    <img src="<?= $lab['backgroundUrl'] ?>" alt="Card Background" class="background-image">
                                    <div class="logo-container">
                                        <img src="<?= $lab['iconeUrl'] ?>" alt="Logo" class="logo-img">
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="card-text-container">
                                        <span class="card-title"><?= $lab['title'] ?></span>
                                        <i id="heart-icon" class="ri-heart-3-line heart-icon"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                <?php }
            ?>
        </div>
    </div>
</section>

<style>

#card {
    margin-top: 20px;


    .card {
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        font-style: normal;
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        background-color: white;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        max-width: 500px;
        margin-top: 30px;
    }

    .card:hover {
        transform: scale(1.02);
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
    }

    .card-img {
        position: relative;
        height: 200px;
    }

    .background-image {
        width: 100%;
        height: 100%;
        object-fit: cover;
        filter: blur(3px);
    }

    .logo-container {
        position: absolute;
        bottom: -5px;
        left: 50%;
        transform: translateX(-50%);
        background-color: white;
        padding: 20px;
        border-radius: 10px 10px 0 0;
    }

    .logo-img {
        width: 70px;
        height: auto;
        z-index: 0;
    }

    .card-body {
        background-color: white;
        z-index: 1;
        padding-bottom: 0px;
    }

    .card-title {
        font-size: 16px;
        font-weight: bold;
        color: #575757;
    }

    .heart-icon {
        color: #0036DE;
        font-size: 32px;
        cursor: pointer;
    }
    /* Class de coeur remplis pour fonction toggle JS au click */
    .ri-heart-3-fill {
        color: blue;
    }

    .clickable-card {
        margin-left: auto;
        margin-right: auto;
        cursor: pointer;
    }

    .card-text-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
        border-top: 1px solid black;
    }
}

</style>

