<footer class="bd-footer py-4 py-md-3 mt-5 bg-white tyro-border">
    <div class="container py-4 py-md-5 px-4 px-md-3 text-body-secondary">
        <div class="row">
        <div class="col-lg-3 mb-3 share-tech-mono">
            <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
            <img src="file_assets/logo.png" width="28" height="27">
            <span class="fs-5">Labs.Tyrolium</span>
            </a>
        </div>
        <div class="col-6 col-lg-2 offset-lg-2 mb-3 text-dark ml-5 share-tech">
            <h5>BUTTOM</h5>
        </div>
        <div class="col-6 col-lg-2 mb-3 text-dark share-tech">
            <h5>BUTTOM</h5>
        </div>
        <div class="col-6 col-lg-2 mb-3 text-dark share-tech">
            <h5>BUTTOM</h5>
        </div>
        </div>
    </div>
</footer>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech&family=Share+Tech+Mono&display=swap');
    .share-tech {
        font-family: "Share Tech", serif;
        font-weight: 400;
        font-style: normal;
    }
    .share-tech-mono {
        font-family: "Share Tech Mono", serif;
        font-weight: 400;
        font-style: normal;
    }
    .tyro-border {
        border-width: thick;
        border-top: solid #132585;
    }
</style>