<footer class="tyro-border">
    <div class="container py-4 py-md-4 text-body-secondary footer-desktop">
        <div class="rowalamano">
        <div class="col-lg-3 share-tech-mono">
            <a class="d-inline-flex align-items-center text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
            <img src="file_assets/logo.png" width="28" height="27">
            <span class="fs-5 px-2">Labs.Tyrolium</span>
            </a>
        </div>
        <div class="col-6 col-lg-2 offset-lg-2 text-dark ml-5 share-tech text-end">
            <h5>BUTTOM</h5>
        </div>
        <div class="col-6 col-lg-2 text-dark share-tech text-end">
            <h5>BUTTOM</h5>
        </div>
        <div class="col-6 col-lg-2 text-dark share-tech text-end">
            <h5>BUTTOM</h5>
        </div>
        </div>
    </div>

    <div class="container py-4 py-md-4 text-body-secondary footer-mobile">
        <div class="col-lg-3 mb-3 share-tech-mono text-center">
            <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
            <img src="file_assets/logo.png" width="28" height="27">
            <span class="fs-5 px-2">Labs.Tyrolium</span>
            </a>
        </div>
        <div class="d-flex flex-row text-dark share-tech justify-content-around">
            <h5>BUTTOM</h5>
            <h5>BUTTOM</h5>
            <h5>BUTTOM</h5>
        </div>
    </div>
</footer>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech&family=Share+Tech+Mono&display=swap');
    footer .share-tech {
        font-family: "Share Tech", serif;
        font-weight: 400;
        font-style: normal;
    }
    footer .share-tech-mono {
        font-family: "Share Tech Mono", serif;
        font-weight: 400;
        font-style: normal;
    }
     footer.tyro-border {
        border-width: thick;
        border-top: solid #0036DE;
    }
    footer h5{
        margin-bottom: unset!important;
    }
    footer .rowalamano{
        display: flex;
        align-items: center;
        justify-content: space-evenly;
    }
    @media (min-width: 992px) {
        footer .footer-mobile {
        display: none;
    }
    }
    @media (max-width: 991px) {
        footer .footer-desktop {
            display: none;
        }
        footer .footer-mobile {
            display: block;
            flex-direction: row;
        }
        footer h5 {
            display: inline-block;
        }
        footer span {
            border-bottom: 2px solid #0028A6;
        }
    }
</style>