<section id="footer">
    <footer class="custom-footer text-center">
        <div class="container-fluid">
            <div class="row pt-2">
                <div class="col-lg-6 logo">
                    <img src="<?= $env_logo ?>" alt="Logo">
                    <p class="fs-2 pt-2">Labs.Tyrolium</p>
                </div>
                <div class="col-lg-6">
                    <button type="button" class="btn btn-primary mx-4">Button</button>
                    <button type="button" class="btn btn-primary m-4">Button</button>
                    <button type="button" class="btn btn-primary mx-4">Button</button>
                </div>
            </div>
        </div>
    </footer>
</section>

<style>
    #footer {
        .custom-footer {
            background-color: rgba(0, 0, 0, 0.05);
            padding: 20px 0;
        }

        .logo {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .logo img {
            height: 50px;
            margin-right: 10px;
        }
    }
</style>