<section id="hero">
    <div class="container">
        <i class="ri-flask-line"></i>
        <h2>Labs.Tyrolium</h2>
        <div class="text-container">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat aspernatur delectus aut autem laborum? Ex dolor delectus quod accusantium iste aliquid dolorum quia. Nulla possimus doloribus culpa voluptates, nobis aliquam! </p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat aspernatur delectus aut autem laborum?</p>
        </div>
    </div>

</section>


<style>

    #hero { 
        background-color: #132585;
        padding-bottom: 20px;
        
        h2 {
            text-align: center;
            padding-bottom: 30px;
            border-bottom: 2px solid #0036DE;
            width: 50%;
            margin: auto;
        }
        
        .text-container {
            text-align: center;
            padding: 20px 20px 0px;
        }

        .container {
            background-color: white;
            padding: 0px 50px 30px 50px;
            border-radius: 0px 0px 15px 15px;
            max-width: 840px;
        }

        i {
            font-size: 96px;
            display: flex;
            justify-content: center;
        }

        @media (max-width: 580px) {
            .container {
                padding: 0px 0px 30px 0px;
            } 
        }

    }



</style>