<section id="hero " >
<div class="bg"  >

  <div class="intro container ">

  <div class="title mx-5 ">
  <p>Labs.Tyrolium</p>
  </div>

  
  </div>

  <div> 

  </div>

</div>
</section>

<style>
.bg{
  background-color: #0036DE ;
  height: 500px;
}

.intro{
  border: 2px solid #0D99FF;
  border-radius: 0px, 0px, 10px, 10px;
  background-color: #fbfbfb;
  height: 450px;
  width: 1300px;

}

.title{
  text-align: center;
  border-bottom: 2px solid #0036DE;
  margin: ;
  

}

</style>