<?php $lab = getOneLabs($_GET['l']) ?>

<section id="heroshow">
    <div id="sliderheroshow">
    </div>

    <div class="container">
        <div class="rowamoi">

            <div class="col-lg-2">
                <div class="d-flex justify-content-center" id="toolLogo">
                    <div id="logo">
                    </div>
                </div>
            </div>
            <div class="offset-lg-2 col-lg-4 desktop-hero">
                <div class="d-flex justify-content-center" id="title">
                    <h1><?= $lab['title'] ?></h1>
                </div>
            </div>
            <div class="offset-lg-2 col-lg-1 desktop-hero">
                <div class="d-flex justify-content-center">
<!--                <i class="ri-heart-3-fill"></i>-->
                    <i onclick="window.location.href = '?l=<?= $lab['id'] ?>&i=t'; " class="ri-heart-3-line"></i>
                </div>
            </div>

        </div>

        <div class="mobile-hero">
            <div class="offset-lg-2 col-lg-4 ">
                <div class="d-fex-perso" id="title">
                    <h1><?= $lab['title'] ?></h1>
                    <i class="ri-heart-3-fill"></i>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="offset-lg-3 col-lg-6">
                <p class="text-center"><?= $lab['content'] ?></p>
            </div>
        </div>

    </div>
</section>


<style>
    #heroshow #toolLogo {
        margin-top: -65px;
        background-color: white;
        border-radius: 10px;
        width: 200px;
        height: 200px;
        align-items: center;
        align-content: center;
        justify-content: center;
        flex-wrap: nowrap;
        flex-direction: row;
    }

    #heroshow #title {
        border-bottom: solid;
        border-color: #0036DE;
    }

    #heroshow h1 {
        font-family: "Shippori Antique", sans-serif;
        font-weight: 400;
        font-style: normal;
    }

    #heroshow i {
        color: #0036DE;
        font-size: 64px;
    }

    #heroshow p {
        font-family: "Share Tech Mono", monospace;
        font-weight: 400;
        font-style: normal
    }

    #heroshow #sliderheroshow{
        height: 299px;
        background-image: url(<?= $lab['background_url'] ?>);
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }

    #heroshow #logo {
        background-image: url(<?= $lab['icon_url'] ?>);
        width: 130px;
        height: 130px;
        background-position: center;
        background-size: contain;
        background-repeat: no-repeat;
    }

    #heroshow .rowamoi{
        display: flex;
        justify-content: center;
        align-items: center;
    }

    #heroshow .mobile-hero{
        display: none;
    }

    #heroshow .d-fex-perso{
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    @media (max-width: 991px) {
        #heroshow .desktop-hero{
            display: none;
        }

        #heroshow .mobile-hero{
            display: block;
            margin-bottom: 50px;
        }

        #heroshow i {
            font-size: 40px;
        }
    }

</style>