<section id = "heroshow">
    <div id = "sliderheroshow">
    </div>

    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2">
                <div class="d-flex justify-content-center" id="toolLogo">
                    <div id="logo">
                    </div>
                </div>
            </div>
            <div class="offset-lg-2 col-lg-4">
                <div class="d-flex justify-content-center" id="title">
                    <h1>TyroSiteFrameWork</h1>
                </div>
            </div>
            <div class="offset-lg-2 col-lg-1">
                <div class="d-flex justify-content-center">
                <i class="ri-heart-3-fill"></i>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="offset-lg-3 col-lg-6">
                <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel  condimentum neque. Suspendisse potenti. Morbi ut orci non ipsum  tincidunt volutpat. Donec viverra lacus ut ultrices ultricies. Quisque  nulla justo, tempor a interdum nec, porta eget ante.</p>
            </div>
        </div>

    </div>
</section>


<style>
    #heroshow #toolLogo {
        margin-top: -65px;
        background-color: white;
        border-radius: 10px;
        width: 200px;
        height: 200px;
        align-items: center;
        align-content: center;
        justify-content: center;
        flex-wrap: nowrap;
    flex-direction: row;
    }

    #heroshow #title {
        border-bottom: solid;
        border-color: #0036DE;
    }

    #heroshow h1 {
        font-family: "Shippori Antique", sans-serif;
        font-weight: 400;
        font-style: normal;
    }

    #heroshow i {
        color: #0036DE;
        font-size: 64px;
    }

    #heroshow p {
        font-family: "Share Tech Mono", monospace;
        font-weight: 400;
        font-style: normal
    }

    #heroshow #sliderheroshow{
        height: 299px;
        background-image: url("https://tyrolium.fr/Contenu/Image/Background23.jpg");
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }

    #heroshow #logo {
        background-image: url('http://localhost/TyroliumLabs-WebSite/file_assets/framework.png');
        width: 130px;
        height: 130px;
        background-position: center;
        background-size: contain;
        background-repeat: no-repeat;
    }

</style>