<section id="hero">
  <div class="bg">
    <div class="intro container">
      <div class="title">
        <i class="ri-flask-line "></i>
        <h1 class=" pb-3 fs-2">Labs.Tyrolium</h1>
      </div>
      <div class=" text-center">
        <p class=" px-5 my-5">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione error beatae autem itaque harum sit maxime quasi at quibusdam sed hic officia laudantium iure fugit, quam non amet accusamus est.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione error beatae autem itaque harum sit maxime quasi at quibusdam sed hic officia laudantium iure fugit, quam non amet accusamus est.Lorem ipsum dolor sit amet consectetur adipisicing elit.
        </p>
      </div>
    </div>
  </div>
</section>

<style>
  #hero {

    .bg {
      background-color: #0036DE;
      height: 450px;
    }

    .intro {
      border-radius: 0px 0px 20px 20px;
      background-color: #fbfbfb;
      height: 410px;
      width: 900px;
    }

    .title {
      text-align: center;
      border-bottom: 4px solid #0036DE;
      margin: 0px 200px 0px 200px;
    }

    i {
      font-size: 80px;
    }

    @media (min-width: 768px) {
      #hero .intro {
        max-width: 80%;
      }
    }
  }
</style>