<section id="moreshow" class="container">
  <div class="row">

    <div class="col-md-6">
      <div class="info-card">
        <div class="info-row">
          <strong class="label">Version :</strong>
          <span class="value">2.0</span>
        </div>
        <div class="info-row">
          <strong class="label">Contributeur :</strong>
          <a href="#" class="value">Maxime Tournier</a>
        </div>
        <div class="info-row">
          <strong class="label">Commit :</strong>
          <span class="value">435</span>
        </div>
        <div class="info-row">
          <strong class="label">Like :</strong>
          <span class="value">8000</span>
        </div>
        <p><strong>Repos : </strong></p>
        <div class="repo-link">
          <i class="ri-github-fill"></i>
          <a href="#">TheMaxium69/TyroSiteFrameWork</a>
        </div>
      </div>  
    </div>
    <!-- Ici l'autre col-md-6 pour la partie usesshow -->
  </div>
</section>


<style>

#moreshow {
  padding: 20px;

    .info-card {
    background-color: #EBE7F6;
    padding: 40px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    font-family: "Share Tech", sans-serif;
    font-weight: 400;
    font-style: normal;
    color: black;
    position: relative;
    }

    .info-row {
      padding: 10px 0;
      text-align: center;
    }

    .info-row .label {
      position: absolute;
      left: 40px;
    }

    .infow-row .value {
      display: block;
      width: 100%;
      text-align: start;
    }

    .info-card p {
    margin: 10px 0;
    }

    .info-card strong {
    color: black;
    font-weight: bold;
    }

    .info-card a {
    color: #012DB6;
    text-decoration: none;
    font-weight: bold;
    }

    .info-card a:hover {
    text-decoration: underline;
    }

    .repo-link {
    display: flex;
    align-items: center;
    }

    .repo-link i {
    color: #012DB6;
    font-size: 24px;
    margin-right: 10px;
    }

    span {
    font-weight: bold;
    color: #012DB6;
    }

}


</style>