<section id="moreshow" class="container">
  <div class="row">

    <div class="col-md-6">
      <div class="info-card">
        <span><strong>Version :</strong></span> <span>2.0</span>
        <p><strong>Contributeur :</strong> <a href="#">Maxime Tournier</a></p>
        <p><strong>Commit :</strong> <span>435</span></p>
        <p><strong>Like :</strong> <span>8000</span></p>
        <p><strong>Repos :</strong></p>
        <div class="repo-link">
          <i class="ri-github-fill"></i>
          <a href="#">TheMaxium69/TyroSiteFrameWork</a>
        </div>
      </div>  
    </div>
    <!-- Ici l'autre col-md-6 pour la partie usesshow -->
  </div>
</section>


<style>

#moreshow {
  padding: 20px;

    .info-card {
    background-color: #EBE7F6;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    font-family: "Share Tech", sans-serif;
    font-weight: 400;
    font-style: normal;
    color: black;
    }

    .info-card p {
    margin: 10px 0;
    }

    .info-card strong {
    color: black;
    font-weight: bold;
    }

    .info-card a {
    color: #012DB6;
    text-decoration: none;
    font-weight: bold;
    }

    .info-card a:hover {
    text-decoration: underline;
    }

    .repo-link {
    display: flex;
    align-items: center;
    }

    .repo-link i {
    color: #012DB6;
    font-size: 24px;
    margin-right: 10px;
    }

    span {
    font-weight: bold;
    color: #012DB6;
    }

}


</style>