<?php 
  $lab = getOneLabs($_GET['l']);

  $repoUrl = $lab['repoUrl'];

  $displayRepo = substr($repoUrl, strlen($repoUrlGlobal));


  $resultGithub = getGithub($displayRepo);


?>

<section id="moreshow">

      <div class="info-card">
        <div class="info-row">
          <strong class="label">Branch :</strong>
          <span class="value"><?= $resultGithub['branch'] ?></span>
        </div>
        <div class="info-row">
          <strong class="label">
              <?php

              $nbContribu = sizeof($resultGithub['contributors']);

              if ($nbContribu == 1) {

                  echo "Contributeur :";
              } else {
                  echo "Contributeurs :";
              }
              ?>
          </strong>
            <div class="row" style="max-width: 63%;">
          <?php
              foreach ($resultGithub['contributors'] as $key => $value) {
                  ?>
                      <div>
                  <a target="_blank" href="<?= $value['url'] ?>" class="value"><?= $value['name'] ?></a>
                      </div><br>
                  <?php
              }
          ?>
            </div>
        </div>
        <div class="info-row">
          <strong class="label">Commit :</strong>
          <span class="value"><?= $resultGithub['commit'] ?></span>
        </div>
        <div class="info-row">
          <strong class="label">Like :</strong>
          <span class="value"><?= $lab['likes'] ?></span>
        </div>
        <p><strong>Repos : </strong></p>
        <div class="repo-link">
          <i class="ri-github-fill"></i>
          <a target="_blank" href="<?= $lab['repoUrl'] ?>"><?= $displayRepo ?></a>
        </div>

  </div>
</section>


<style>

#moreshow {
  padding: 20px;

    .info-card {
    background-color: #EBE7F6;
    padding: 30px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    font-family: "Share Tech", sans-serif;
    font-weight: 400;
    font-style: normal;
    color: black;
    position: relative;
    }

    .info-row {
      display: flex;
      align-items: center;
      padding: 10px 0;
    }

    .info-row .label {
      width: 150px;
      text-align: left;
      margin-right: 20px;
  
    }

    .infow-row .value {
      text-align: left;
      padding-left: 30px;
      min-width: 100px;
    }

    .info-card p {
    margin: 10px 0;
    }

    .info-card strong {
    color: black;
    font-weight: bold;
    }

    .info-card a {
    color: #012DB6;
    text-decoration: none;
    font-weight: bold;
    }

    .info-card a:hover {
    text-decoration: underline;
    }

    .repo-link {
    display: flex;
    align-items: center;
    }

    .repo-link i {
    color: #012DB6;
    font-size: 24px;
    margin-right: 10px;
    }

    span {
    font-weight: bold;
    color: #012DB6;
    }

    

}


</style>