
<section id="navbar">
<nav class="fixed-top navbar navbar-expand-lg bg-body-tertiary fs-6">
    <div class="container-fluid">
        <a class="navbar-brand" href=".">
            <img src="<?= $env_logo ?>" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
            
            <a href="index.php" class="name-logo">Labs.Tyrolium</a>
        </a>
        <div class="collapse navbar-collapse d-flex justify-content-end d-lg-flex" id="navbarNav" style="display: flex !important;
    flex-basis: auto;">
            <ul class="navbar-nav mx-2" style="
    flex-direction: row;">
                <li onclick="window.location.href='https://tyrolium.fr';"><i class="ri-global-line mx-2"></i></li>
                <li onclick="window.location.href='https://discord.gg/mtDx9ceS7n';"><i class="ri-discord-fill"></i></li>
            </ul>
            <a href="https://tyrolium.fr/contact" class="btn-contact">Contactez-nous</a>
        </div>
    </div>
</nav>
</section>



<style>
 #navbar {

     background-color: rgb(248,249,250);
     height: 60px;

     .navbar{
         width: 100%;
         padding: 0.5rem 19px;
         box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.25);
     }


    .btn-contact{
        background-color: #0036DE;
        border-radius: 20px;
        padding: 10px;
        text-decoration: none;
        color:white;
        box-shadow:3px 3px 5px rgba(0, 0, 0, 0.5);
    }

    .name-logo{
        text-decoration: none;
        color:black;
        border-bottom: 2px solid #0036DE;
    }

 }

 @media (max-width: 439px) {

     #navbar .navbar-nav{
         display: none;
     }



 }


</style>