<section id="uses">
    <h4>Projets qui utilisent ce Lab:</h4>
    
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <a href="" target="_blank">
                <i class="ri-global-line"></i>
            </a>
            <a href="" target="_blank">
                <i class="ri-github-fill"></i>
            </a>
        </div>
    </div>
    <div class="border-item mb-2 mt-2"></div>
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <a href="" target="_blank">
                    <i class="ri-global-line"></i>
                </a>
            <a href="" target="_blank">
                <i class="ri-github-fill"></i>
            </a>
        </div>
    </div>
    <div class="border-item mb-2 mt-2"></div>
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <a href="" target="_blank">
                    <i class="ri-global-line"></i>
            </a>
            <a href="" target="_blank">
                    <i class="ri-github-fill"></i>
            </a>
        </div>
    </div>
    <div class="border-item mb-2 mt-2"></div>


</section>

<style>
    #uses {
        padding: 20px;

        h4 {
            border-top: 2px solid #0036DE;
            padding: 15px 0px;
            text-decoration: underline;
        }

        .row-item {
            padding: 0px 30px;
            width: auto;
            justify-content: space-between;
        }

        .row-item p {
            margin: 0;
            align-content: center;
        }

        .icon-container i {
            color: #0036DE;
            font-size: 28px;
        }

        .icon-container a {
            text-decoration: none;
        }

        .border-item {
            height: 1px;
            width: 85%;
            background-color: black;
            margin: auto;
        }

    }

</style>