<?php

$projectAll = getProjectByLabs($_GET['l']);

?>

<section id="uses">
    <h4>Projets qui utilisent ce Lab:</h4>

    <?php if (empty($projectAll)) {?>
        <small>Aucun projet public n'utilise actuellement ce Lab</small>

    <?php } ?>
    
    <?php foreach ($projectAll as $project) { ?>
        <div class="row-item d-flex">

            <p><?= $project['title'] ?></p>
            
            <div class="icon-container">
                <?php if (!empty($project['websiteUrl'])) { ?>
                <a href="<?= $project['websiteUrl'] ?>" target="_blank">
                    <i class="ri-global-line"></i>
                </a>
                <?php } ?>
                <?php if (!empty($project['repoUrl'])) { ?>
                <a href="<?= $project['repoUrl'] ?>" target="_blank">
                    <i class="ri-github-fill"></i>
                </a>
                <?php } ?>
            </div>

        </div>
        
        <div class="border-item mb-2 mt-2"></div>
    <?php } ?>


</section>

<style>
    #uses {
        padding: 20px;

        h4 {
            border-top: 2px solid #0036DE;
            padding: 15px 0px;
            text-decoration: underline;
        }

        .row-item {
            min-height: 40px;
            padding: 0px 30px;
            width: auto;
            justify-content: space-between;
        }

        .row-item p {
            margin: 0;
            align-content: center;
        }

        .icon-container i {
            color: #0036DE;
            font-size: 28px;
        }

        .icon-container a {
            text-decoration: none;
        }

        .border-item {
            height: 1px;
            width: 85%;
            background-color: black;
            margin: auto;
        }

    }

</style>