<section id="uses" class="col-lg-6">
    <h4>Projets qui utilisent ce Lab:</h4>
    
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <i class="ri-global-line"></i>
            <i class="ri-github-fill"></i>
        </div>
    </div>
    <div class="border-item mb-4"></div>
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <i class="ri-global-line"></i>
            <i class="ri-github-fill"></i>
        </div>
    </div>
    <div class="border-item mb-4"></div>
    <div class="row-item d-flex">
        <p>Tyrolium Site</p>
        <div class="icon-container">
            <i class="ri-global-line"></i>
            <i class="ri-github-fill"></i>
        </div>
    </div>
    <div class="border-item mb-4"></div>


</section>

<style>
    #uses {
        padding: 10px;

        h4 {
            border-top: 2px solid #0036DE;
            padding: 15px 0px;
            text-decoration: underline;
        }

        .row-item {
            padding: 0px 30px;
            width: auto;
            justify-content: space-between;
        }

        .icon-container i {
            color: #0036DE;
        }

        .border-item {
            height: 1px;
            width: 80%;
            background-color: black;
            margin: auto;
        }

    }

</style>